### PR TITLE
fix: [1618] query only repo matching uuid and role to properly suppor…

### PR DESCRIPTION
**Pull request by xangxiong**
…t team/user that may have more than 10 repo

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by minz1027** [comment]
@xangxiong it seems like the PR build didn’t run. I merged it and it failed the tests in production. Can you open another PR to fix the unit tests. Thanks!

**Comment by xangxiong** [comment]
Sure, I will take a look at the unit test and adjust as needed.

**Comment by xangxiong** [comment]
@minz1027 , created pull request https://github.com/screwdriver-cd/scm-bitbucket/pull/59 to merge in the updated unit tests.

**Pull request merged**
